services:
  backend:
    build: ./backend
    container_name: mindx-backend
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    container_name: mindx-frontend
    ports:
      - "3000:80"
